### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-nello: Error: Cannot find module './functions/connectWebhook'

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-nello#10]
Hi Guys,

thanks for the update to v0.3.0.
I updated like always with `sudo npm install -g homebridge-homebridge-nello` but now get the error below.
I didn't change the config.json for now to keep it simple and only use the previous basics.

Am I doing something wrong or missing something?

Thanks in advance.

```
  {
            "platform": "NelloPlatform",
            "name": "Haustür",
            "username": "xxx@gmail.com",
            "password": "xxxxx",
            "locationUpdateInterval": 3600000,
            "activityUpdateInterval": 0,
            "lockTimeout": 5000
        },
```

```
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]: [2018-6-16 00:54:01] ERROR LOADING PLUGIN homebridge-nello:
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]: [2018-6-16 00:54:01] Error: Cannot find module './functions/connectWebhook'
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Module.require (internal/modules/cjs/loader.js:650:17)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at require (internal/modules/cjs/helpers.js:20:18)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-nello/index.js:146:42)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Module._compile (internal/modules/cjs/loader.js:702:30)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Module.load (internal/modules/cjs/loader.js:612:32)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
Jun 16 00:54:01 raspberrypi-3BPlus homebridge[5804]:     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by AlexanderBabel** [comment]
Fixed in v0.3.1
