### ISSUE TITLE
Crashing homebridge during initializing platform

### ISSUE THREAD

**Issue by krmkrx** [lukasroegner/homebridge-nello#12]
Hi there. I have used @AlexanderBabel fork without any issues previously.
However, after updating to 0.3.2. my homebridge crashes:

```
Jun 17 01:43:00 raspberrypi homebridge[32748]: [6/17/2018, 1:43:00 AM] [nello.io] Initializing NelloPlatform platform...
Jun 17 01:43:00 raspberrypi homebridge[32748]: /usr/local/lib/node_modules/homebridge-nello/index.js:55
Jun 17 01:43:00 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jun 17 01:43:00 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Jun 17 01:43:00 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

Config is as follows:

```
      {
         "platform":"NelloPlatform",
         "name":"nello.io",
         "username":"xxx",
         "password":"xxx",
         "lockTimeout":30000,
         "locationUpdateInterval":3600000,
         "exposeReachability":false,
         "videoDoorbell":true,
  "video": {
                "snapshotImage": "http://www.solidbackgrounds.com/images/1280x720/1280x720-black-solid-color-background.jpg"
            },
            "homekitUser": "HomeKit Apple"
      },
```

Any idea on what might be wrong?
Deleting accessories/persist folders did not help.

**Comment by krmkrx** [comment]
Sorry @AlexanderBabel , need to reopen. Log outputs another issue now after updating to 0.3.3.:

```
Jun 17 02:04:47 raspberrypi homebridge[3425]: [6/17/2018, 2:04:47 AM] [nello.io] Adding new accessory with location ID xxx.
Jun 17 02:04:47 raspberrypi homebridge[3425]: [6/17/2018, 2:04:47 AM] [nello.io] Accessory name for location ID xxx is xxx.
Jun 17 02:04:47 raspberrypi homebridge[3425]: [6/17/2018, 2:04:47 AM] [nello.io] Configuring accessory with location ID xxx.
Jun 17 02:04:47 raspberrypi homebridge[3425]: /usr/local/lib/node_modules/homebridge-nello/functions/addAccessory.js:36
Jun 17 02:04:47 raspberrypi homebridge[3425]:     platform.api.registerPlatformAccessories(pluginName, platformName, [accessory]);
Jun 17 02:04:47 raspberrypi homebridge[3425]:                                              ^
Jun 17 02:04:47 raspberrypi homebridge[3425]: ReferenceError: pluginName is not defined
Jun 17 02:04:47 raspberrypi homebridge[3425]:     at NelloPlatform.module.exports [as addAccessory] (/usr/local/lib/node_modules/homebridge-nello/functions/addAccessory.js:36:46)
Jun 17 02:04:47 raspberrypi homebridge[3425]:     at Request._callback (/usr/local/lib/node_modules/homebridge-nello/functions/updateLocations.js:85:26)
Jun 17 02:04:47 raspberrypi homebridge[3425]:     at Request.self.callback (/usr/local/lib/node_modules/homebridge-nello/node_modules/request/request.js:185:22)
Jun 17 02:04:47 raspberrypi homebridge[3425]:     at Request.emit (events.js:182:13)
Jun 17 02:04:47 raspberrypi homebridge[3425]:     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nello/node_modules/request/request.js:1157:10)
Jun 17 02:04:47 raspberrypi homebridge[3425]:     at Request.emit (events.js:182:13)
Jun 17 02:04:47 raspberrypi homebridge[3425]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nello/node_modules/request/request.js:1079:12)
Jun 17 02:04:47 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jun 17 02:04:47 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Jun 17 02:04:47 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by AlexanderBabel** [comment]
Please try this one:
```bash
npm i git+https://github.com/lukasroegner/homebridge-nello.git
```

I updated the repo but did not published a new update. If it works I will publish it.

Greetings
Alex

**Comment by krmkrx** [comment]
Hi Alex,

I can confirm that the above version is working. Thank you.

Best,
Karim
