### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by romanvrable** [lukasroegner/homebridge-nello#31]
Running into  the UUID already existing problem, therefore not able to start plugin. Already tried to uninstall/install hombridge and plugin. Also tried to delete accessories and persist folder. First time I am using the plugin, so cannot report on any changes since an update. 
```
[11/26/2018, 1:25:17 AM] [nello.io] Cached accessories loaded.
[11/26/2018, 1:25:17 AM] [nello.io] Getting locations from nello.io.
[11/26/2018, 1:25:17 AM] [nello.io] Signing in.
[11/26/2018, 1:25:17 AM] Homebridge is running on port 5182.
[11/26/2018, 1:25:18 AM] [nello.io] Signed in.
[11/26/2018, 1:25:18 AM] [nello.io] Getting locations from nello.io.
[11/26/2018, 1:25:18 AM] [nello.io] Adding new accessory with location ID 952951e3-93ce-494c-9900-50a8760eda8a.
[11/26/2018, 1:25:18 AM] [nello.io] Accessory name for location ID 952951e3-93ce-494c-9900-50a8760eda8a is XXX .
[11/26/2018, 1:25:18 AM] [nello.io] Configuring accessory with location ID 952951e3-93ce-494c-9900-50a8760eda8a.
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b9f33d00-e2cc-4e26-ae25-afa2f865105d
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:290:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:473:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:41:10)
    at API.emit (events.js:182:13)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:159:8)
    at NelloPlatform.module.exports [as addAccessory] (/usr/local/lib/node_modules/homebridge-nello/functions/addAccessory.js:33:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nello/functions/updateLocations.js:85:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nello/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
```

**Comment by lukasroegner** [comment]
@izecell Is this issue still occurring?

**Comment by romanvrable** [comment]
@lukasroegner Yes, it is still occurring, nothing changed so far

**Comment by lukasroegner** [comment]
Have you already tried to clear the homebridge cache? It seems that another device with the same ID is already listed in the cache file. 

Keep in mind that your device settings are lost when removing the cache, maybe you can use another homebridge instance to test whether it is an issue with your network components, our plugin, or simply the cache of your homebridge instance.
